{{- $gatewayName := include "controlplane.fullname" . -}}
{{- $name := include "controlplane.organizationName" . -}}
{{- $svcPort := .Values.organization.service.httpPort -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $gatewayName }}-organization
  labels:
    authentication/zitadel: organization
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gatewayName }}
  hostnames:
  {{- range .Values.recordNames }}
    - {{ . }}
  {{- end }}
  rules:
  {{- range .Values.organization.gatewayAPI.hosts }}
    {{- range .paths }}
    - matches:
      {{- if .methods }}
        {{- range .methods }}
        - path:
            type: {{ $.pathType }}
            value: {{ $.path }}
          method: {{ . }}
        {{- end }}
      {{- else }}
        - path:
            type: {{ .pathType }}
            value: {{ .path }}
          method: GET
      {{- end }}
      backendRefs:
        - name: {{ $name }}
          port: {{ $svcPort }}
    {{- end }}
  {{- end }}

