apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlplane.organizationName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.organization.service.type }}
  ports:
    - port: {{ .Values.organization.service.gRPCPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.organization.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "controlplane.selectorLabelsOrganization" . | nindent 4 }}
