{{- if .Values.organization.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controlplane.serviceAccountOrganizationName" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
  {{- with .Values.organization.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.organization.serviceAccount.automount }}
{{- end }}
