imagePullSecrets:
- name: dockerconfigjson-github-com

nameOverride: ""
fullnameOverride: ""

stage: "dev"
recordNames:
- "app.dev.roclub.io"

serviceAccount:
  create: true
  annotations: {}
  name: ""

resources: {}

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector:
  beta.kubernetes.io/arch: arm64 
tolerations: []
affinity: {}

httpRoute:
  enabled: true

appSecrets:
  authSecret:
    secretKey: ""
  zitadelIssuer:
    secretKey: ""
  zitadelClientId:
    secretKey: ""
  zitadelClientSecret:
    secretKey: ""
  nextauthUrl:
    secretKey: ""
  zitadelUserSa:
    secretKey: ""
  zitadelSecretSa:
    secretKey: ""
  zitadelBaseUrl:
    secretKey: ""
  zitadelProjectID:
    secretKey: ""

image:
  tag: ""
  repository: ghcr.io/roclub/app-development
  pullPolicy: Always
  
replicaCount: 1

service:
  type: ClusterIP
  port: 8080

