apiVersion: v1
kind: Secret
metadata:
  name: app-nextjs
type: Opaque
stringData:
  auth_secret: "{{ .Values.appSecrets.authSecret.secretKey }}"
  zitadel_issuer: "{{ .Values.appSecrets.zitadelIssuer.secretKey }}"
  zitadel_client_id: "{{ .Values.appSecrets.zitadelClientId.secretKey }}"
  zitadel_client_secret: "{{ .Values.appSecrets.zitadelClientSecret.secretKey }}"
  nextauth_url: "{{ .Values.appSecrets.nextauthUrl.secretKey }}"
  next_zitadel_user_sa: "{{ .Values.appSecrets.nextZitadelUserSa.secretKey }}"
  next_zitadel_secret_sa: "{{ .Values.appSecrets.nextZitadelSecretSa.secretKey }}"
  next_public_base_url: "{{ .Values.appSecrets.nextPublicBaseUrl.secretKey }}"
  next_public_zitadel_base_url: "{{ .Values.appSecrets.nextPublicZitadelBaseUrl.secretKey }}"

