apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-app-nextjs
type: Opaque
stringData:
  auth_secret: "{{ .Values.appSecrets.authSecret.secretKey }}"
  zitadel_issuer: "{{ .Values.appSecrets.zitadelIssuer.secretKey }}"
  zitadel_client_id: "{{ .Values.appSecrets.zitadelClientId.secretKey }}"
  zitadel_client_secret: "{{ .Values.appSecrets.zitadelClientSecret.secretKey }}"
  nextauth_url: "{{ .Values.appSecrets.nextauthUrl.secretKey }}"
  zitadel_user_sa: "{{ .Values.appSecrets.zitadelUserSa.secretKey }}"
  zitadel_secret_sa: "{{ .Values.appSecrets.zitadelSecretSa.secretKey }}"
  zitadel_project_id: "{{ .Values.appSecrets.zitadelProjectID.secretKey }}"
  zitadel_base_url: "{{ .Values.appSecrets.zitadelBaseUrl.secretKey }}"

